### ISSUE TITLE
attribute error value.tzinfo = none related to openWB integration

### ISSUE THREAD

**Issue by ChristophCaina** [ChristophCaina/openwbmqtt#20]
```
Logger: homeassistant
Source: components/sensor/__init__.py:408
First occurred: 11:12:20 (4 occurrences)
Last logged: 11:13:50
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 397, in state
    if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 740, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 408, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.openwb_cp1_voraus_ladeende has a timestamp device class but does not provide a datetime state but <class 'str'>
```

**Comment by ChristophCaina** [comment]
related log event:

```
 Logger: homeassistant.util.logging
Source: util/logging.py:116
First occurred: 11:11:56 (7 occurrences)
Last logged: 11:12:56

    Exception in message_received when handling msg on 'openWB/lp/1/TimeRemaining': ' Min' Traceback (most recent call last): File "/config/custom_components/openwbmqtt/sensor.py", line 144, in message_received delta = timedelta(minutes=int(tmp[0])) ValueError: invalid literal for int() with base 10: 'Min'
    Exception in message_received when handling msg on 'openWB/lp/1/TimeRemaining': '- Min' Traceback (most recent call last): File "/config/custom_components/openwbmqtt/sensor.py", line 144, in message_received delta = timedelta(minutes=int(tmp[0])) ValueError: invalid literal for int() with base 10: '-'
```

**Comment by ChristophCaina** [comment]
if no charging is active, the sensor is just sending the below string.
![grafik](https://user-images.githubusercontent.com/26391061/194128168-11fa2985-e92c-4a11-902f-0a58fd670971.png)

**Comment by ChristophCaina** [comment]
TimeRemaining will be removed from the integration, since it does not provide a valid date and time.
This needs probably fixed in the openWB sourcecode for a more correct calculation.

**Comment by ChristophCaina** [comment]
issue probably related with one of my template sensors which should change the format.
this is now being fixed in the integration directly.
