### ISSUE TITLE
Uptime formatter throws error

### ISSUE THREAD

**Issue by onkelbeh** [ChristophCaina/openwbmqtt#23]
openwb reports uptime in mins while hour=0:

```
2022-09-24 08:22:55.736 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'openWB/openWB/system/Uptime': ' 08:22:54 up 3 days, 39 min,  1 user,  load average: 1,33, 1,16, 1,11'
Traceback (most recent call last):
  File "/etc/homeassistant/custom_components/openwbmqtt/sensor.py", line 154, in message_received
    mins = hourmins[2:].split(":")[1]
IndexError: list index out of range
```

**Comment by onkelbeh** [comment]
in addition, we don't have days in the very first 24 hours:

```
2022-09-24 08:57:25.712 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'openWB/openWB/system/Uptime': ' 08:57:24 up 2 min,  1 user,  load average: 1,97, 1,08, 0,43'
Traceback (most recent call last):
  File "/etc/homeassistant/custom_components/openwbmqtt/sensor.py", line 154, in message_received
    mins = hourmins[2:].split(":")[1]
IndexError: list index out of range
```
I would expect the following formats:

First hour:
`uptime=' 08:56:57 up 2 min,  1 user,  load average: 2,25, 1,05, 0,40'`

rest of the first day:
`uptime=' 08:52:12 up 12:43,  3 users,  load average: 0,02, 0,05, 0,07'`

first hour of 2nd day:
`uptime=' 09:01:53 up 1 day, 13:31,  1 user,  load average: 0.00, 0.00, 0.00'`

rest of time:
`uptime=' 08:50:04 up 3 days,  1:06,  1 user,  load average: 1,60, 2,10, 1,61'`
