### ISSUE TITLE
'DeviceRegistry' object has no attribute '_update_device'

### ISSUE THREAD

**Issue by ChristophCaina** [ChristophCaina/openwbmqtt#27]
```
Logger: homeassistant.util.logging
Source: util/logging.py:168
First occurred: 19:33:23 (80 occurrences)
Last logged: 22:44:18

Exception in message_received when handling msg on 'openWB/system/IpAddress': '192.168.52.71' Traceback (most recent call last): File "/config/custom_components/openwbmqtt/sensor.py", line 176, in message_received device_registry._update_device AttributeError: 'DeviceRegistry' object has no attribute '_update_device'
Exception in message_received when handling msg on 'openWB/system/Version': '1.9.277' Traceback (most recent call last): File "/config/custom_components/openwbmqtt/sensor.py", line 186, in message_received device_registry._update_device AttributeError: 'DeviceRegistry' object has no attribute '_update_device'
```

**Comment by ChristophCaina** [comment]
this is the affected code area:
```
            # If MQTT message contains IP --> set up configuration_url to visit the device
            elif "ip_adresse" in self.entity_id:
                device_registry = async_get_dev_reg(self.hass)
                device = device_registry.async_get_device(
                    self.device_info.get("identifiers")
                )
                device_registry.async_update_device(
                    device.id,
                    configuration_url=f"http://{message.payload}/openWB/web/index.php",
                )
                device_registry._update_device
            # If MQTT message contains version --> set sw_version of the device
            elif "version" in self.entity_id:
                device_registry = async_get_dev_reg(self.hass)
                device = device_registry.async_get_device(
                    self.device_info.get("identifiers")
                )
                device_registry.async_update_device(
                    device.id, sw_version=message.payload
                )
                device_registry._update_device
```

**Comment by onkelbeh** [comment]
same here:

```
2022-10-07 15:01:41.034 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'openWB/openWB/system/IpAddress': '172.16.4.50'
Traceback (most recent call last):
  File "/etc/homeassistant/custom_components/openwbmqtt/sensor.py", line 174, in message_received
    device_registry._update_device
AttributeError: 'DeviceRegistry' object has no attribute '_update_device'

2022-10-07 15:01:41.038 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'openWB/openWB/system/Version': '1.9.281'
Traceback (most recent call last):
  File "/etc/homeassistant/custom_components/openwbmqtt/sensor.py", line 184, in message_received
    device_registry._update_device
AttributeError: 'DeviceRegistry' object has no attribute '_update_device'
```

**Comment by ChristophCaina** [comment]
It is most probably related to the last line in the Elif:

`device_registry._update_device`

I am just not sure if this can be removed or needs to be changed to `device_registry.async_update_device`

**Comment by onkelbeh** [comment]
You have a PR.

**Comment by onkelbeh** [comment]
additionally I double checked that the values are updated in device registry:

<img width="1323" alt="grafik" src="https://user-images.githubusercontent.com/42828703/194693693-e1632eb3-f692-4c87-992d-7e36fd367ec4.png">

<img width="605" alt="grafik" src="https://user-images.githubusercontent.com/42828703/194693811-02be7101-45b9-4e61-914b-d20f58161b98.png">
